import ast
from pathlib import Path

from tools import stub_common

OUT_PATH: Path = stub_common.OUT_PATH / "mod_api.lua"

TYPE_MAP = {
    "int": "integer",
    "float": "number",
    "str": "string",
    "bool": "boolean",
    "bytes": "string",
    "Callable": "function",
    "dict": "table",
    "list": "table",
    "Any": "any",
}

def flatten_union(annotation: ast.expr) -> list[ast.expr]:
    if isinstance(annotation, ast.BinOp) and isinstance(annotation.op, ast.BitOr):
        return flatten_union(annotation.left) + flatten_union(annotation.right)
    return [annotation]

def subscript_args(annotation: ast.Subscript) -> list[ast.expr]:
    """`tuple[int, str]` -> [int, str], `list[int]` -> [int]."""
    return annotation.slice.elts if isinstance(annotation.slice, ast.Tuple) else [annotation.slice]

def lua_type(annotation: ast.expr | None) -> str:
    if annotation is None:
        return "any"
    if isinstance(annotation, ast.Constant):
        return "nil" if annotation.value is None else "any"
    if isinstance(annotation, ast.Name):
        return TYPE_MAP.get(annotation.id, annotation.id)
    if isinstance(annotation, ast.Attribute):
        return annotation.attr
    if isinstance(annotation, ast.BinOp):
        parts = list(dict.fromkeys(lua_type(a) for a in flatten_union(annotation)))
        return "|".join(sorted(parts, key=lambda p: p == "nil"))
    if isinstance(annotation, ast.Subscript):
        kind = ast.unparse(annotation.value)
        args = subscript_args(annotation)
        if kind == "Callable":
            return "function"
        if kind in ("list", "set", "frozenset"):
            return f"{lua_type(args[0])}[]"
        if kind == "dict" and len(args) == 2:
            return f"table<{lua_type(args[0])}, {lua_type(args[1])}>"
        return "table"
    return "any"

def lua_returns(returns: ast.expr | None) -> list[str]:
    if returns is None or (isinstance(returns, ast.Constant) and returns.value is None):
        return []
    if isinstance(returns, ast.Subscript) and ast.unparse(returns.value) == "tuple":
        return [lua_type(a) for a in subscript_args(returns)]
    if isinstance(returns, ast.BinOp):
        parts = flatten_union(returns)
        tuples = [p for p in parts if isinstance(p, ast.Subscript) and ast.unparse(p.value) == "tuple"]
        has_none = any(isinstance(p, ast.Constant) and p.value is None for p in parts)
        if len(tuples) == 1 and has_none and len(parts) == 2:
            return [f"{lua_type(a)}|nil" for a in subscript_args(tuples[0])]
    return [lua_type(returns)]

def generate_method_stub(cls: ast.ClassDef, method: ast.FunctionDef) -> list[str]:
    lines: list[str] = []
    doc = ast.get_docstring(method)
    if doc:
        lines += [f"---{line}" for line in doc.splitlines()]

    args = method.args.args
    first_default = len(args) - len(method.args.defaults)
    arg_names: list[str] = []
    for i, arg in enumerate(args[1:], start=1):
        arg_names.append(arg.arg)
        optional = "?" if i >= first_default else ""
        lines.append(f"---@param {arg.arg}{optional} {lua_type(arg.annotation)}")
    if method.args.vararg:
        arg_names.append("...")
        lines.append(f"---@param ... {lua_type(method.args.vararg.annotation)}")

    lines += [f"---@return {ret}" for ret in lua_returns(method.returns)]
    lines.append(f"function {cls.name}.{method.name}({', '.join(arg_names)}) end")
    lines.append("")
    return lines

def generate_class_stub(cls: ast.ClassDef, lines: list[str]) -> None:
    doc = ast.get_docstring(cls)
    if doc:
        lines += [f"---{line}" for line in doc.splitlines()]
    lines.append(f"---@class {cls.name}")
    field_docs = stub_common.field_docs(cls)
    for name, annotation in stub_common.public_fields(cls):
        description = f" {' '.join(field_docs[name].split())}" if name in field_docs else ""
        lines.append(f"---@field {name} {lua_type(annotation)}{description}")
    for prop in stub_common.public_properties(cls):
        doc = ast.get_docstring(prop)
        description = f" {' '.join(doc.split())}" if doc else ""
        lines.append(f"---@field {prop.name} {lua_type(prop.returns)}{description}")
    prefix = "" if cls.name == stub_common.ROOT else "local "
    lines.append(f"{prefix}{cls.name} = {{}}")
    lines.append("")

    for method in stub_common.public_methods(cls):
        lines.extend(generate_method_stub(cls, method))
    for nested in stub_common.nested_classes(cls):
        generate_class_stub(nested, lines)

def write_stub(out_path: Path=OUT_PATH) -> None:
    """Writes `mod_api.lua`."""
    lines: list[str] = ["---@meta", "-- Auto-generated by tools/generate_lua_stubs.py. Do not edit.", ""]
    for name, value in stub_common.collect_aliases().items():
        lines += [f"---@alias {name} {lua_type(value)}", ""]
    for cls in stub_common.collect_used_classes(stub_common.collect_classes()):
        generate_class_stub(cls, lines)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f'File generated in "{out_path}"')

if __name__ == "__main__":
    write_stub()
