import ast
from pathlib import Path

import stub_common

OUT_PATH: Path = stub_common.OUT_PATH / "mod_api.lua"

TYPE_MAP = {
    "int": "integer",
    "float": "number",
    "str": "string",
    "bool": "boolean",
    "bytes": "string",
}

def flatten_union(annotation: ast.expr) -> list[ast.expr]:
    if isinstance(annotation, ast.BinOp) and isinstance(annotation.op, ast.BitOr):
        return flatten_union(annotation.left) + flatten_union(annotation.right)
    return [annotation]

def subscript_args(annotation: ast.Subscript) -> list[ast.expr]:
    """`tuple[int, str]` -> [int, str], `list[int]` -> [int]."""
    return annotation.slice.elts if isinstance(annotation.slice, ast.Tuple) else [annotation.slice]

def lua_type(annotation: ast.expr | None) -> str:
    if annotation is None:
        return "any"
    if isinstance(annotation, ast.Constant):
        return "nil" if annotation.value is None else "any"
    if isinstance(annotation, ast.Name):
        return TYPE_MAP.get(annotation.id, annotation.id)
    if isinstance(annotation, ast.Attribute):
        return annotation.attr
    if isinstance(annotation, ast.BinOp):
        parts = list(dict.fromkeys(lua_type(a) for a in flatten_union(annotation)))
        return "|".join(sorted(parts, key=lambda p: p == "nil"))
    if isinstance(annotation, ast.Subscript):
        kind = ast.unparse(annotation.value)
        args = subscript_args(annotation)
        if kind in ("list", "set", "frozenset"):
            return f"{lua_type(args[0])}[]"
        if kind == "dict" and len(args) == 2:
            return f"table<{lua_type(args[0])}, {lua_type(args[1])}>"
        return "table"
    return "any"

def lua_returns(returns: ast.expr | None) -> list[str]:
    if returns is None or (isinstance(returns, ast.Constant) and returns.value is None):
        return []
    if isinstance(returns, ast.Subscript) and ast.unparse(returns.value) == "tuple":
        return [lua_type(a) for a in subscript_args(returns)]
    return [lua_type(returns)]

def generate_method_stub(cls: ast.ClassDef, method: ast.FunctionDef) -> list[str]:
    lines: list[str] = []
    doc = ast.get_docstring(method)
    if doc:
        lines += [f"---{line}" for line in doc.splitlines()]

    args = method.args.args
    first_default = len(args) - len(method.args.defaults)
    arg_names: list[str] = []
    for i, arg in enumerate(args[1:], start=1):
        arg_names.append(arg.arg)
        optional = "?" if i >= first_default else ""
        lines.append(f"---@param {arg.arg}{optional} {lua_type(arg.annotation)}")
    if method.args.vararg:
        arg_names.append("...")
        lines.append(f"---@param ... {lua_type(method.args.vararg.annotation)}")

    lines += [f"---@return {ret}" for ret in lua_returns(method.returns)]
    lines.append(f"function {cls.name}.{method.name}({', '.join(arg_names)}) end")
    lines.append("")
    return lines

def generate_class_stub(cls: ast.ClassDef, lines: list[str]) -> None:
    lines.append(f"---@class {cls.name}")
    for name, annotation in stub_common.public_fields(cls):
        lines.append(f"---@field {name} {lua_type(annotation)}")
    prefix = "" if cls.name == stub_common.ROOT else "local "
    lines.append(f"{prefix}{cls.name} = {{}}")
    lines.append("")

    for method in stub_common.public_methods(cls):
        lines.extend(generate_method_stub(cls, method))
    for nested in stub_common.nested_classes(cls):
        generate_class_stub(nested, lines)

def write_stub(out_path: Path=OUT_PATH) -> None:
    lines: list[str] = ["---@meta", "-- Auto-generated by tools/generate_lua_stubs.py. Do not edit.", ""]
    for cls in stub_common.collect_used_classes(stub_common.collect_classes()):
        generate_class_stub(cls, lines)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")

if __name__ == "__main__":
    write_stub()
