import ast
import sys
from pathlib import Path

import config

DESKTOP_DIR = config.APP_DIR / "desktop"
SOURCES = [DESKTOP_DIR / "mod_api.py", DESKTOP_DIR / "mods_manager.py", DESKTOP_DIR / "input_events.py"]
OUT_PATH: Path = config.APP_DIR / "tools" / "output" / "stubs" / "mod_api.pyi"
ROOT = "ModAPI"

# ---- Reading the sources (identical in generate_lua_stubs.py) ----

def collect_classes() -> dict[str, ast.ClassDef]:
    """Top-level classes from SOURCES by name (nested classes stay inside their parent)."""
    classes: dict[str, ast.ClassDef] = {}
    for path in SOURCES:
        for node in ast.parse(path.read_text(encoding="utf-8")).body:
            if isinstance(node, ast.ClassDef):
                classes[node.name] = node
    return classes

def public_methods(cls: ast.ClassDef) -> list[ast.FunctionDef]:
    return [n for n in cls.body if isinstance(n, ast.FunctionDef) and not n.name.startswith("_")]

def public_fields(cls: ast.ClassDef) -> list[tuple[str, ast.expr | None]]:
    """Class-level fields and `self.X: T = ...` declared in __init__, as (name, annotation)."""
    fields: list[tuple[str, ast.expr | None]] = []
    for node in cls.body:
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            fields.append((node.target.id, node.annotation))
        elif isinstance(node, ast.Assign):
            fields += [(t.id, None) for t in node.targets if isinstance(t, ast.Name)]
        elif isinstance(node, ast.FunctionDef) and node.name == "__init__":
            for stmt in ast.walk(node):
                if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Attribute):
                    fields.append((stmt.target.attr, stmt.annotation))
    return [(name, annotation) for name, annotation in fields if not name.startswith("_")]

def nested_classes(cls: ast.ClassDef) -> list[ast.ClassDef]:
    return [n for n in cls.body if isinstance(n, ast.ClassDef)]

def annotations(cls: ast.ClassDef) -> list[ast.expr]:
    """Every annotation in the public API of the class (including nested classes)."""
    result = [annotation for _, annotation in public_fields(cls) if annotation]
    for method in public_methods(cls):
        result += [a.annotation for a in method.args.args if a.annotation]
        if method.returns:
            result.append(method.returns)
    for nested in nested_classes(cls):
        result += annotations(nested)
    return result

def collect_used_classes(classes: dict[str, ast.ClassDef]) -> list[ast.ClassDef]:
    """ROOT + every class referenced from its annotations (transitively)."""
    used: dict[str, ast.ClassDef] = {}
    queue = [ROOT]
    while queue:
        name = queue.pop(0)
        if name in used or name not in classes:
            continue
        used[name] = classes[name]
        queue += [n.id for a in annotations(classes[name]) for n in ast.walk(a) if isinstance(n, ast.Name)]
    return list(used.values())

# ---- Python specific ----

def is_stdlib(module: str | None) -> bool:
    return module is not None and module.split(".")[0] in sys.stdlib_module_names

def collect_imports() -> list[str]:
    """Stdlib imports from SOURCES (annotations like `Path | None` need them)."""
    imports: list[str] = []
    for path in SOURCES:
        for node in ast.parse(path.read_text(encoding="utf-8")).body:
            if isinstance(node, ast.ImportFrom) and node.level == 0 and is_stdlib(node.module):
                imports.append(ast.unparse(node))
            elif isinstance(node, ast.Import) and all(is_stdlib(a.name) for a in node.names):
                imports.append(ast.unparse(node))
    return list(dict.fromkeys(imports))

def python_source(node: ast.AST) -> str:
    return ast.unparse(node).replace(f"{ROOT}.", "")

def generate_method_stub(method: ast.FunctionDef) -> list[str]:
    returns = f" -> {python_source(method.returns)}" if method.returns else ""
    lines = [f"    def {method.name}({python_source(method.args)}){returns}:"]
    doc = ast.get_docstring(method)
    if doc:
        lines.append(f'        """{doc}"""')
    lines.append("        ...")
    lines.append("")
    return lines

def generate_class_stub(cls: ast.ClassDef, lines: list[str]) -> None:
    name = f"_{cls.name}" if cls.name == ROOT else cls.name
    bases = ", ".join(python_source(b) for b in cls.bases)
    lines.append(f"class {name}({bases}):" if bases else f"class {name}:")
    body_start = len(lines)
    for field, annotation in public_fields(cls):
        lines.append(f"    {field}: {python_source(annotation)}" if annotation else f"    {field} = ...")
    lines.append("")

    for method in public_methods(cls):
        lines.extend(generate_method_stub(method))
    if len(lines) == body_start + 1:
        lines.insert(body_start, "    ...")
    for nested in nested_classes(cls):
        generate_class_stub(nested, lines)

def write_stub(out_path: Path = OUT_PATH) -> None:
    lines: list[str] = ["# Auto-generated by tools/generate_python_stubs.py. Do not edit.", *collect_imports(), ""]
    for cls in collect_used_classes(collect_classes()):
        generate_class_stub(cls, lines)
    lines += [f"{ROOT}: _{ROOT}", ""]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")

if __name__ == "__main__":
    write_stub()
