import ast
import sys
import textwrap
from pathlib import Path

from tools import stub_common

OUT_PATH: Path = stub_common.OUT_PATH / "mod_api.pyi"

def is_stdlib(module: str | None) -> bool:
    return module is not None and module.split(".")[0] in sys.stdlib_module_names

def collect_imports(used: set[str]) -> list[str]:
    """Stdlib imports from SOURCES that the annotations and base classes of the stub use (e.g. `Path | None`)."""
    plain: list[str] = []
    from_imports: dict[str, list[str]] = {}
    for path in stub_common.SOURCES:
        for node in ast.parse(path.read_text(encoding="utf-8")).body:
            if isinstance(node, ast.ImportFrom) and node.level == 0 and node.module and is_stdlib(node.module):
                for alias in node.names:
                    if (alias.asname or alias.name) in used:
                        names = from_imports.setdefault(node.module, [])
                        text = ast.unparse(alias)
                        if text not in names:
                            names.append(text)
            elif isinstance(node, ast.Import):
                for alias in node.names:
                    text = ast.unparse(ast.Import(names=[alias]))
                    if is_stdlib(alias.name) and (alias.asname or alias.name.split(".")[0]) in used and text not in plain:
                        plain.append(text)
    return plain + [f"from {module} import {', '.join(names)}" for module, names in from_imports.items()]

def python_source(node: ast.AST) -> str:
    return ast.unparse(node).replace(f"{stub_common.ROOT}.", "")

def docstring(doc: str, indent: str) -> str:
    """A docstring whose continuation lines are indented too."""
    return f'{indent}"""{textwrap.indent(doc, indent).lstrip()}"""'

def generate_method_stub(method: ast.FunctionDef) -> list[str]:
    returns = f" -> {python_source(method.returns)}" if method.returns else ""
    lines = []
    if stub_common.is_property(method):
        lines.append("    @property")
    lines.append(f"    def {method.name}({python_source(method.args)}){returns}:")
    doc = ast.get_docstring(method)
    if doc:
        lines.append(docstring(doc, "        "))
    lines.append("        ...")
    lines.append("")
    return lines

def generate_class_stub(cls: ast.ClassDef, lines: list[str]) -> None:
    name = f"_{cls.name}" if cls.name == stub_common.ROOT else cls.name
    bases = ", ".join(python_source(b) for b in cls.bases)
    lines.append(f"class {name}({bases}):" if bases else f"class {name}:")
    body_start = len(lines)
    doc = ast.get_docstring(cls)
    if doc:
        lines.append(docstring(doc, "    "))
    field_docs = stub_common.field_docs(cls)
    for field, annotation in stub_common.public_fields(cls):
        lines.append(f"    {field}: {python_source(annotation)}" if annotation else f"    {field} = ...")
        if field in field_docs:
            lines.append(docstring(field_docs[field], "    "))
    lines.append("")

    for prop in stub_common.public_properties(cls):
        lines.extend(generate_method_stub(prop))
    for method in stub_common.public_methods(cls):
        lines.extend(generate_method_stub(method))
    if len(lines) == body_start + 1:
        lines.insert(body_start, "    ...")
    for nested in stub_common.nested_classes(cls):
        generate_class_stub(nested, lines)

def write_stub(out_path: Path=OUT_PATH) -> None:
    """Writes `mod_api.pyi`."""
    classes = stub_common.collect_used_classes(stub_common.collect_classes())
    lines: list[str] = ["# Auto-generated by tools/generate_python_stubs.py. Do not edit.", *collect_imports(stub_common.used_names(classes)), ""]
    for name, value in stub_common.collect_aliases().items():
        lines += [f"{name} = {python_source(value)}", ""]
    for cls in classes:
        generate_class_stub(cls, lines)
    lines += [f"{stub_common.ROOT}: _{stub_common.ROOT}", ""]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f'File generated in "{out_path}"')

if __name__ == "__main__":
    write_stub()
