import ast
import sys
from pathlib import Path

import stub_common

OUT_PATH: Path = stub_common.OUT_PATH / "mod_api.pyi"

def is_stdlib(module: str | None) -> bool:
    return module is not None and module.split(".")[0] in sys.stdlib_module_names

def collect_imports() -> list[str]:
    """Stdlib imports from SOURCES (annotations like `Path | None` need them)."""
    imports: list[str] = []
    for path in stub_common.SOURCES:
        for node in ast.parse(path.read_text(encoding="utf-8")).body:
            if isinstance(node, ast.ImportFrom) and node.level == 0 and is_stdlib(node.module):
                imports.append(ast.unparse(node))
            elif isinstance(node, ast.Import) and all(is_stdlib(a.name) for a in node.names):
                imports.append(ast.unparse(node))
    return list(dict.fromkeys(imports))

def python_source(node: ast.AST) -> str:
    return ast.unparse(node).replace(f"{stub_common.ROOT}.", "")

def generate_method_stub(method: ast.FunctionDef) -> list[str]:
    returns = f" -> {python_source(method.returns)}" if method.returns else ""
    lines = [f"    def {method.name}({python_source(method.args)}){returns}:"]
    doc = ast.get_docstring(method)
    if doc:
        lines.append(f'        """{doc}"""')
    lines.append("        ...")
    lines.append("")
    return lines

def generate_class_stub(cls: ast.ClassDef, lines: list[str]) -> None:
    name = f"_{cls.name}" if cls.name == stub_common.ROOT else cls.name
    bases = ", ".join(python_source(b) for b in cls.bases)
    lines.append(f"class {name}({bases}):" if bases else f"class {name}:")
    body_start = len(lines)
    for field, annotation in stub_common.public_fields(cls):
        lines.append(f"    {field}: {python_source(annotation)}" if annotation else f"    {field} = ...")
    lines.append("")

    for method in stub_common.public_methods(cls):
        lines.extend(generate_method_stub(method))
    if len(lines) == body_start + 1:
        lines.insert(body_start, "    ...")
    for nested in stub_common.nested_classes(cls):
        generate_class_stub(nested, lines)

def write_stub(out_path: Path=OUT_PATH) -> None:
    lines: list[str] = ["# Auto-generated by tools/generate_python_stubs.py. Do not edit.", *collect_imports(), ""]
    for cls in stub_common.collect_used_classes(stub_common.collect_classes()):
        generate_class_stub(cls, lines)
    lines += [f"{stub_common.ROOT}: _{stub_common.ROOT}", ""]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")

if __name__ == "__main__":
    write_stub()
